name: Push to Discord

on:
  push:
    branches: [development]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"✅ Push auf development von ${{ github.actor }}: ${{ github.event.head_commit.message }}"}' \
               https://discord.com/api/webhooks/1395160362252242964/aT96BEckdNORrm96GTsueD_FjcIPsQduxFTEGpTGMZzRzBP6z6Wf-HaDMsp03HibrzcI
